# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemist_Master', '0003_alter_chemistregister_chemistpwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
