# Generated by Codex on 2026-06-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Master', '0002_alter_userregister_userpwd'),
        ('Chemist_Master', '0004_productdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetails',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Master.userregister'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Master.userregister'),
        ),
        migrations.AddField(
            model_name='sk_bills',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Master.userregister'),
        ),
    ]
